version: '3.8'

services:
  php:
    build: .
    container_name: symfony_php
    volumes:
      - .:/var/www/symfony
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d
    networks:
      - symfony-network

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    volumes:
      - .:/var/www/symfony
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - symfony-network

networks:
  symfony-network:
    driver: bridge
