version: '3.8'

services:
  vue-app:
    build: .
    container_name: katavuejs
    ports:
      - "8081:80"  # Map port 8081 on the host to port 80 in the container (Nginx default)
    volumes:
      - .:/app
    networks:
      - vue-network

networks:
  vue-network:
    driver: bridge
